//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulatina.Electiva.AdventureWorks.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract] 
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductReviews = new HashSet<ProductReview>();
        }
    
        [DataMember]
     public int ProductID { get; set; }
        [DataMember]
     public string Name { get; set; }
        [DataMember]
     public string ProductNumber { get; set; }
        [DataMember]
     public bool MakeFlag { get; set; }
        [DataMember]
     public bool FinishedGoodsFlag { get; set; }
        [DataMember]
     public string Color { get; set; }
        [DataMember]
     public short SafetyStockLevel { get; set; }
        [DataMember]
     public short ReorderPoint { get; set; }
        [DataMember]
     public decimal StandardCost { get; set; }
        [DataMember]
     public decimal ListPrice { get; set; }
        [DataMember]
     public string Size { get; set; }
        [DataMember]
     public string SizeUnitMeasureCode { get; set; }
        [DataMember]
     public string WeightUnitMeasureCode { get; set; }
        [DataMember]
     public Nullable<decimal> Weight { get; set; }
        [DataMember]
     public int DaysToManufacture { get; set; }
        [DataMember]
     public string ProductLine { get; set; }
        [DataMember]
     public string Class { get; set; }
        [DataMember]
     public string Style { get; set; }
        [DataMember]
     public Nullable<int> ProductSubcategoryID { get; set; }
        [DataMember]
     public Nullable<int> ProductModelID { get; set; }
        [DataMember]
     public System.DateTime SellStartDate { get; set; }
        [DataMember]
     public Nullable<System.DateTime> SellEndDate { get; set; }
        [DataMember]
     public Nullable<System.DateTime> DiscontinuedDate { get; set; }
        [DataMember]
     public System.Guid rowguid { get; set; }
        [DataMember]
     public System.DateTime ModifiedDate { get; set; }
    
        public virtual ProductModel ProductModel { get; set; }
        public virtual ProductSubcategory ProductSubcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductReview> ProductReviews { get; set; }
    }
}
