//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulatina.Electiva.AdventureWorks.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract] 
    public partial class ProductReview
    {
        [DataMember]
     public int ProductReviewID { get; set; }
        [DataMember]
     public int ProductID { get; set; }
        [DataMember]
     public string ReviewerName { get; set; }
        [DataMember]
     public System.DateTime ReviewDate { get; set; }
        [DataMember]
     public string EmailAddress { get; set; }
        [DataMember]
     public int Rating { get; set; }
        [DataMember]
     public string Comments { get; set; }
        [DataMember]
     public System.DateTime ModifiedDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
