//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulatina.PruebaProyecto.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EstudianteCurso
    {
        [Key]
        public int IdEstudiante { get; set; }
        [Key]
        public int IdCurso { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<byte> Unidad { get; set; }
        public Nullable<byte> Nota { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
