//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityOfProductcmA0XIUh", Namespace="http://schemas.datacontract.org/2004/07/Ulatina.Topicos.GenericRepository.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ulatina.Electiva.AdventureWorks.Model.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ulatina.Electiva.AdventureWorks.BL.CompositeType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>))]
    public partial class EntityOfProductcmA0XIUh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object UlatinaTopicosGenericRepositoryModelIEntity_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ulatina.Electiva.AdventureWorks.Model.Product _IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> _ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] _VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> createdDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Ulatina.Topicos.GenericRepository.Model.IEntity._Id")]
        public object UlatinaTopicosGenericRepositoryModelIEntity_Id {
            get {
                return this.UlatinaTopicosGenericRepositoryModelIEntity_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.UlatinaTopicosGenericRepositoryModelIEntity_IdField, value) != true)) {
                    this.UlatinaTopicosGenericRepositoryModelIEntity_IdField = value;
                    this.RaisePropertyChanged("UlatinaTopicosGenericRepositoryModelIEntity_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _CreatedBy {
            get {
                return this._CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this._CreatedByField, value) != true)) {
                    this._CreatedByField = value;
                    this.RaisePropertyChanged("_CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _CreatedDate {
            get {
                return this._CreatedDateField;
            }
            set {
                if ((this._CreatedDateField.Equals(value) != true)) {
                    this._CreatedDateField = value;
                    this.RaisePropertyChanged("_CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ulatina.Electiva.AdventureWorks.Model.Product _Id {
            get {
                return this._IdField;
            }
            set {
                if ((object.ReferenceEquals(this._IdField, value) != true)) {
                    this._IdField = value;
                    this.RaisePropertyChanged("_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ModifiedBy {
            get {
                return this._ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this._ModifiedByField, value) != true)) {
                    this._ModifiedByField = value;
                    this.RaisePropertyChanged("_ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> _ModifiedDate {
            get {
                return this._ModifiedDateField;
            }
            set {
                if ((this._ModifiedDateField.Equals(value) != true)) {
                    this._ModifiedDateField = value;
                    this.RaisePropertyChanged("_ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Name {
            get {
                return this._NameField;
            }
            set {
                if ((object.ReferenceEquals(this._NameField, value) != true)) {
                    this._NameField = value;
                    this.RaisePropertyChanged("_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] _Version {
            get {
                return this._VersionField;
            }
            set {
                if ((object.ReferenceEquals(this._VersionField, value) != true)) {
                    this._VersionField = value;
                    this.RaisePropertyChanged("_Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> createdDate {
            get {
                return this.createdDateField;
            }
            set {
                if ((this.createdDateField.Equals(value) != true)) {
                    this.createdDateField = value;
                    this.RaisePropertyChanged("createdDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SI.AdventureWorks.IAdventureWorksWcf")]
    public interface IAdventureWorksWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/GetData", ReplyAction="http://tempuri.org/IAdventureWorksWcf/GetDataResponse")]
        Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataResponse GetData(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/GetData", ReplyAction="http://tempuri.org/IAdventureWorksWcf/GetDataResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataResponse> GetDataAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAdventureWorksWcf/GetDataUsingDataContractResponse")]
        Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataUsingDataContractResponse GetDataUsingDataContract(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAdventureWorksWcf/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ListarProductos", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ListarProductosResponse")]
        Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ListarProductosResponse ListarProductos(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ListarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ListarProductos", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ListarProductosResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ListarProductosResponse> ListarProductosAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ListarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/BuscarProductoPorNumero", ReplyAction="http://tempuri.org/IAdventureWorksWcf/BuscarProductoPorNumeroResponse")]
        Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.BuscarProductoPorNumeroResponse BuscarProductoPorNumero(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.BuscarProductoPorNumeroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/BuscarProductoPorNumero", ReplyAction="http://tempuri.org/IAdventureWorksWcf/BuscarProductoPorNumeroResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.BuscarProductoPorNumeroResponse> BuscarProductoPorNumeroAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.BuscarProductoPorNumeroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeProducto", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeProductoResponse")]
        Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeProductoResponse ConsultarPorNombreDeProducto(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeProducto", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeProductoResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeProductoResponse> ConsultarPorNombreDeProductoAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorColor", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorColorResponse")]
        Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorColorResponse ConsultarPorColor(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorColorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorColor", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorColorResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorColorResponse> ConsultarPorColorAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorColorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorPrecio", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorPrecioResponse")]
        Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorPrecioResponse ConsultarPorPrecio(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorPrecioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorPrecio", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorPrecioResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorPrecioResponse> ConsultarPorPrecioAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorPrecioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorTamano", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorTamanoResponse")]
        Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorTamanoResponse ConsultarPorTamano(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorTamanoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorTamano", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorTamanoResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorTamanoResponse> ConsultarPorTamanoAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorTamanoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeSubcategoria", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeSubcategoriaResponse")]
        Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeSubcategoriaResponse ConsultarPorNombreDeSubcategoria(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeSubcategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeSubcategoria", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeSubcategoriaResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeSubcategoriaResponse> ConsultarPorNombreDeSubcategoriaAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeSubcategoriaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(int value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataResult;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Ulatina.Electiva.AdventureWorks.BL.CompositeType composite;
        
        public GetDataUsingDataContractRequest() {
        }
        
        public GetDataUsingDataContractRequest(Ulatina.Electiva.AdventureWorks.BL.CompositeType composite) {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Ulatina.Electiva.AdventureWorks.BL.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse() {
        }
        
        public GetDataUsingDataContractResponse(Ulatina.Electiva.AdventureWorks.BL.CompositeType GetDataUsingDataContractResult) {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarProductos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarProductosRequest {
        
        public ListarProductosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarProductosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ListarProductosResult;
        
        public ListarProductosResponse() {
        }
        
        public ListarProductosResponse(System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ListarProductosResult) {
            this.ListarProductosResult = ListarProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarProductoPorNumero", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscarProductoPorNumeroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string miNumeroDeProducto;
        
        public BuscarProductoPorNumeroRequest() {
        }
        
        public BuscarProductoPorNumeroRequest(string miNumeroDeProducto) {
            this.miNumeroDeProducto = miNumeroDeProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuscarProductoPorNumeroResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuscarProductoPorNumeroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Ulatina.Electiva.AdventureWorks.Model.Product BuscarProductoPorNumeroResult;
        
        public BuscarProductoPorNumeroResponse() {
        }
        
        public BuscarProductoPorNumeroResponse(Ulatina.Electiva.AdventureWorks.Model.Product BuscarProductoPorNumeroResult) {
            this.BuscarProductoPorNumeroResult = BuscarProductoPorNumeroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorNombreDeProducto", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorNombreDeProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string elNombreDelProducto;
        
        public ConsultarPorNombreDeProductoRequest() {
        }
        
        public ConsultarPorNombreDeProductoRequest(string elNombreDelProducto) {
            this.elNombreDelProducto = elNombreDelProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorNombreDeProductoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorNombreDeProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorNombreDeProductoResult;
        
        public ConsultarPorNombreDeProductoResponse() {
        }
        
        public ConsultarPorNombreDeProductoResponse(System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorNombreDeProductoResult) {
            this.ConsultarPorNombreDeProductoResult = ConsultarPorNombreDeProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorColor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorColorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string elColor;
        
        public ConsultarPorColorRequest() {
        }
        
        public ConsultarPorColorRequest(string elColor) {
            this.elColor = elColor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorColorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorColorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorColorResult;
        
        public ConsultarPorColorResponse() {
        }
        
        public ConsultarPorColorResponse(System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorColorResult) {
            this.ConsultarPorColorResult = ConsultarPorColorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorPrecio", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorPrecioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal elPrecioMinimo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal elPrecioMaximo;
        
        public ConsultarPorPrecioRequest() {
        }
        
        public ConsultarPorPrecioRequest(decimal elPrecioMinimo, decimal elPrecioMaximo) {
            this.elPrecioMinimo = elPrecioMinimo;
            this.elPrecioMaximo = elPrecioMaximo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorPrecioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorPrecioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorPrecioResult;
        
        public ConsultarPorPrecioResponse() {
        }
        
        public ConsultarPorPrecioResponse(System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorPrecioResult) {
            this.ConsultarPorPrecioResult = ConsultarPorPrecioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorTamano", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorTamanoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string elTamano;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool incluirNulos;
        
        public ConsultarPorTamanoRequest() {
        }
        
        public ConsultarPorTamanoRequest(string elTamano, bool incluirNulos) {
            this.elTamano = elTamano;
            this.incluirNulos = incluirNulos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorTamanoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorTamanoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorTamanoResult;
        
        public ConsultarPorTamanoResponse() {
        }
        
        public ConsultarPorTamanoResponse(System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorTamanoResult) {
            this.ConsultarPorTamanoResult = ConsultarPorTamanoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorNombreDeSubcategoria", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorNombreDeSubcategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string elNombreDeLaSubcategoria;
        
        public ConsultarPorNombreDeSubcategoriaRequest() {
        }
        
        public ConsultarPorNombreDeSubcategoriaRequest(string elNombreDeLaSubcategoria) {
            this.elNombreDeLaSubcategoria = elNombreDeLaSubcategoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorNombreDeSubcategoriaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConsultarPorNombreDeSubcategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorNombreDeSubcategoriaResult;
        
        public ConsultarPorNombreDeSubcategoriaResponse() {
        }
        
        public ConsultarPorNombreDeSubcategoriaResponse(System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorNombreDeSubcategoriaResult) {
            this.ConsultarPorNombreDeSubcategoriaResult = ConsultarPorNombreDeSubcategoriaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdventureWorksWcfChannel : Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.IAdventureWorksWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdventureWorksWcfClient : System.ServiceModel.ClientBase<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.IAdventureWorksWcf>, Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.IAdventureWorksWcf {
        
        public AdventureWorksWcfClient() {
        }
        
        public AdventureWorksWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdventureWorksWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureWorksWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureWorksWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataResponse GetData(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataResponse> GetDataAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataUsingDataContractResponse GetDataUsingDataContract(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ListarProductosResponse ListarProductos(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ListarProductosRequest request) {
            return base.Channel.ListarProductos(request);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ListarProductosResponse> ListarProductosAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ListarProductosRequest request) {
            return base.Channel.ListarProductosAsync(request);
        }
        
        public Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.BuscarProductoPorNumeroResponse BuscarProductoPorNumero(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.BuscarProductoPorNumeroRequest request) {
            return base.Channel.BuscarProductoPorNumero(request);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.BuscarProductoPorNumeroResponse> BuscarProductoPorNumeroAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.BuscarProductoPorNumeroRequest request) {
            return base.Channel.BuscarProductoPorNumeroAsync(request);
        }
        
        public Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeProductoResponse ConsultarPorNombreDeProducto(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeProductoRequest request) {
            return base.Channel.ConsultarPorNombreDeProducto(request);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeProductoResponse> ConsultarPorNombreDeProductoAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeProductoRequest request) {
            return base.Channel.ConsultarPorNombreDeProductoAsync(request);
        }
        
        public Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorColorResponse ConsultarPorColor(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorColorRequest request) {
            return base.Channel.ConsultarPorColor(request);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorColorResponse> ConsultarPorColorAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorColorRequest request) {
            return base.Channel.ConsultarPorColorAsync(request);
        }
        
        public Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorPrecioResponse ConsultarPorPrecio(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorPrecioRequest request) {
            return base.Channel.ConsultarPorPrecio(request);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorPrecioResponse> ConsultarPorPrecioAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorPrecioRequest request) {
            return base.Channel.ConsultarPorPrecioAsync(request);
        }
        
        public Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorTamanoResponse ConsultarPorTamano(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorTamanoRequest request) {
            return base.Channel.ConsultarPorTamano(request);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorTamanoResponse> ConsultarPorTamanoAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorTamanoRequest request) {
            return base.Channel.ConsultarPorTamanoAsync(request);
        }
        
        public Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeSubcategoriaResponse ConsultarPorNombreDeSubcategoria(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeSubcategoriaRequest request) {
            return base.Channel.ConsultarPorNombreDeSubcategoria(request);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeSubcategoriaResponse> ConsultarPorNombreDeSubcategoriaAsync(Ulatina.Electiva.AdventureWorks.Tests.SI.AdventureWorks.ConsultarPorNombreDeSubcategoriaRequest request) {
            return base.Channel.ConsultarPorNombreDeSubcategoriaAsync(request);
        }
    }
}
