//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulatina.Electiva.Classwork.Training.SI.AdventureWorks {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Ulatina.Electiva.AdventureWorks.BL")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityOfProductcmA0XIUh", Namespace="http://schemas.datacontract.org/2004/07/Ulatina.Topicos.GenericRepository.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ulatina.Electiva.AdventureWorks.Model.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.CompositeType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.ProductsViewModel>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ulatina.Electiva.AdventureWorks.Model.ProductsViewModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>))]
    public partial class EntityOfProductcmA0XIUh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object UlatinaTopicosGenericRepositoryModelIEntity_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ulatina.Electiva.AdventureWorks.Model.Product _IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> _ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] _VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> createdDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Ulatina.Topicos.GenericRepository.Model.IEntity._Id")]
        public object UlatinaTopicosGenericRepositoryModelIEntity_Id {
            get {
                return this.UlatinaTopicosGenericRepositoryModelIEntity_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.UlatinaTopicosGenericRepositoryModelIEntity_IdField, value) != true)) {
                    this.UlatinaTopicosGenericRepositoryModelIEntity_IdField = value;
                    this.RaisePropertyChanged("UlatinaTopicosGenericRepositoryModelIEntity_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _CreatedBy {
            get {
                return this._CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this._CreatedByField, value) != true)) {
                    this._CreatedByField = value;
                    this.RaisePropertyChanged("_CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _CreatedDate {
            get {
                return this._CreatedDateField;
            }
            set {
                if ((this._CreatedDateField.Equals(value) != true)) {
                    this._CreatedDateField = value;
                    this.RaisePropertyChanged("_CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ulatina.Electiva.AdventureWorks.Model.Product _Id {
            get {
                return this._IdField;
            }
            set {
                if ((object.ReferenceEquals(this._IdField, value) != true)) {
                    this._IdField = value;
                    this.RaisePropertyChanged("_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ModifiedBy {
            get {
                return this._ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this._ModifiedByField, value) != true)) {
                    this._ModifiedByField = value;
                    this.RaisePropertyChanged("_ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> _ModifiedDate {
            get {
                return this._ModifiedDateField;
            }
            set {
                if ((this._ModifiedDateField.Equals(value) != true)) {
                    this._ModifiedDateField = value;
                    this.RaisePropertyChanged("_ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _Name {
            get {
                return this._NameField;
            }
            set {
                if ((object.ReferenceEquals(this._NameField, value) != true)) {
                    this._NameField = value;
                    this.RaisePropertyChanged("_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] _Version {
            get {
                return this._VersionField;
            }
            set {
                if ((object.ReferenceEquals(this._VersionField, value) != true)) {
                    this._VersionField = value;
                    this.RaisePropertyChanged("_Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> createdDate {
            get {
                return this.createdDateField;
            }
            set {
                if ((this.createdDateField.Equals(value) != true)) {
                    this.createdDateField = value;
                    this.RaisePropertyChanged("createdDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SI.AdventureWorks.IAdventureWorksWcf")]
    public interface IAdventureWorksWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/GetData", ReplyAction="http://tempuri.org/IAdventureWorksWcf/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/GetData", ReplyAction="http://tempuri.org/IAdventureWorksWcf/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAdventureWorksWcf/GetDataUsingDataContractResponse")]
        Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.CompositeType GetDataUsingDataContract(Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAdventureWorksWcf/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.CompositeType> GetDataUsingDataContractAsync(Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ListarProductosParaViewModel", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ListarProductosParaViewModelResponse")]
        System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.ProductsViewModel> ListarProductosParaViewModel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ListarProductosParaViewModel", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ListarProductosParaViewModelResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.ProductsViewModel>> ListarProductosParaViewModelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ListarProductos", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ListarProductosResponse")]
        System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ListarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ListarProductos", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ListarProductosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ListarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/BuscarProductoPorNumero", ReplyAction="http://tempuri.org/IAdventureWorksWcf/BuscarProductoPorNumeroResponse")]
        Ulatina.Electiva.AdventureWorks.Model.Product BuscarProductoPorNumero(string miNumeroDeProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/BuscarProductoPorNumero", ReplyAction="http://tempuri.org/IAdventureWorksWcf/BuscarProductoPorNumeroResponse")]
        System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Model.Product> BuscarProductoPorNumeroAsync(string miNumeroDeProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeProducto", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeProductoResponse")]
        System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorNombreDeProducto(string elNombreDelProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeProducto", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorNombreDeProductoAsync(string elNombreDelProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorColor", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorColorResponse")]
        System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorColor(string elColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorColor", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorColorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorColorAsync(string elColor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorPrecio", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorPrecioResponse")]
        System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorPrecio(decimal elPrecioMinimo, decimal elPrecioMaximo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorPrecio", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorPrecioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorPrecioAsync(decimal elPrecioMinimo, decimal elPrecioMaximo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorTamano", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorTamanoResponse")]
        System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorTamano(string elTamano, bool incluirNulos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorTamano", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorTamanoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorTamanoAsync(string elTamano, bool incluirNulos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeSubcategoria", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeSubcategoriaResponse")]
        System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorNombreDeSubcategoria(string elNombreDeLaSubcategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeSubcategoria", ReplyAction="http://tempuri.org/IAdventureWorksWcf/ConsultarPorNombreDeSubcategoriaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorNombreDeSubcategoriaAsync(string elNombreDeLaSubcategoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdventureWorksWcfChannel : Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.IAdventureWorksWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdventureWorksWcfClient : System.ServiceModel.ClientBase<Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.IAdventureWorksWcf>, Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.IAdventureWorksWcf {
        
        public AdventureWorksWcfClient() {
        }
        
        public AdventureWorksWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdventureWorksWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureWorksWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureWorksWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.CompositeType GetDataUsingDataContract(Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.CompositeType> GetDataUsingDataContractAsync(Ulatina.Electiva.Classwork.Training.SI.AdventureWorks.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.ProductsViewModel> ListarProductosParaViewModel() {
            return base.Channel.ListarProductosParaViewModel();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.ProductsViewModel>> ListarProductosParaViewModelAsync() {
            return base.Channel.ListarProductosParaViewModelAsync();
        }
        
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ListarProductos() {
            return base.Channel.ListarProductos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ListarProductosAsync() {
            return base.Channel.ListarProductosAsync();
        }
        
        public Ulatina.Electiva.AdventureWorks.Model.Product BuscarProductoPorNumero(string miNumeroDeProducto) {
            return base.Channel.BuscarProductoPorNumero(miNumeroDeProducto);
        }
        
        public System.Threading.Tasks.Task<Ulatina.Electiva.AdventureWorks.Model.Product> BuscarProductoPorNumeroAsync(string miNumeroDeProducto) {
            return base.Channel.BuscarProductoPorNumeroAsync(miNumeroDeProducto);
        }
        
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorNombreDeProducto(string elNombreDelProducto) {
            return base.Channel.ConsultarPorNombreDeProducto(elNombreDelProducto);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorNombreDeProductoAsync(string elNombreDelProducto) {
            return base.Channel.ConsultarPorNombreDeProductoAsync(elNombreDelProducto);
        }
        
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorColor(string elColor) {
            return base.Channel.ConsultarPorColor(elColor);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorColorAsync(string elColor) {
            return base.Channel.ConsultarPorColorAsync(elColor);
        }
        
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorPrecio(decimal elPrecioMinimo, decimal elPrecioMaximo) {
            return base.Channel.ConsultarPorPrecio(elPrecioMinimo, elPrecioMaximo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorPrecioAsync(decimal elPrecioMinimo, decimal elPrecioMaximo) {
            return base.Channel.ConsultarPorPrecioAsync(elPrecioMinimo, elPrecioMaximo);
        }
        
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorTamano(string elTamano, bool incluirNulos) {
            return base.Channel.ConsultarPorTamano(elTamano, incluirNulos);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorTamanoAsync(string elTamano, bool incluirNulos) {
            return base.Channel.ConsultarPorTamanoAsync(elTamano, incluirNulos);
        }
        
        public System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product> ConsultarPorNombreDeSubcategoria(string elNombreDeLaSubcategoria) {
            return base.Channel.ConsultarPorNombreDeSubcategoria(elNombreDeLaSubcategoria);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Ulatina.Electiva.AdventureWorks.Model.Product>> ConsultarPorNombreDeSubcategoriaAsync(string elNombreDeLaSubcategoria) {
            return base.Channel.ConsultarPorNombreDeSubcategoriaAsync(elNombreDeLaSubcategoria);
        }
    }
}
